# Generated by Django 5.1 on 2024-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('github_link', models.URLField(max_length=255)),
                ('live_link', models.URLField(max_length=255)),
                ('price_quoted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('project_status', models.CharField(choices=[('awaiting_customer', 'Awaiting Customer'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100)),
                ('final_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
