# Generated by Django 5.1 on 2024-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0004_alter_project_final_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
