# Generated by Django 5.1 on 2024-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0005_alter_project_github_link_alter_project_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
