# Generated by Django 5.1 on 2024-09-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0007_projectmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CSP.project'),
            preserve_default=False,
        ),
    ]
