# Generated by Django 5.1 on 2024-09-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_message_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interest',
            field=models.CharField(choices=[('design', 'Website Design'), ('development', 'Website Development'), ('ecommerce', 'E-Commerce'), ('other', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
