# Generated by Django 5.1 on 2024-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
