# Generated by Django 5.1 on 2024-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_portfolio_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='excerpt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
